# Generated by Django 4.2.14 on 2026-01-07 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Витрата'), ('income', 'Дохід')], default='expense', max_length=10, verbose_name='Тип')),
                ('category', models.CharField(default='Інше', max_length=50, verbose_name='Категорія')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('description', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операції')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.balanceitem', verbose_name='Рахунок')),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Транзакції',
                'ordering': ['-created_at'],
            },
        ),
    ]
