# Generated by Django 4.2.14 on 2026-01-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balanceitem',
            options={'verbose_name': 'Рахунок', 'verbose_name_plural': 'Рахунки'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфель', 'verbose_name_plural': 'Портфелі'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Їжа та продукти'), ('transport', 'Транспорт і пальне'), ('entertainment', 'Розваги'), ('utilities', 'Комунальні'), ('shopping', 'Шопінг'), ('apartment', 'Дім та оренда'), ('transfer', 'Переказ'), ('salary', 'Зарплата'), ('other', 'Інше')], default='other', max_length=50, verbose_name='Категорія'),
        ),
    ]
