# Generated by Django 4.2.14 on 2026-01-07 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_balanceitem_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата переказу')),
                ('description', models.TextField(blank=True, verbose_name='Коментар')),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.balanceitem', verbose_name='З рахунку')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.balanceitem', verbose_name='На рахунок')),
            ],
            options={
                'verbose_name': 'Переказ',
                'verbose_name_plural': 'Перекази',
                'ordering': ['-created_at'],
            },
        ),
    ]
