# Generated by Django 4.2.14 on 2026-01-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
                ('icon', models.CharField(blank=True, default='📦', max_length=50, verbose_name='Іконка (емодзі або клас)')),
                ('color', models.CharField(blank=True, default='secondary', max_length=20, verbose_name='Колір (Bootstrap клас)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.category', verbose_name='Категорія'),
        ),
    ]
