# Generated by Django 4.2.14 on 2026-01-08 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('start_date', models.DateField()),
                ('next_payment_date', models.DateField()),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Щомісяця'), ('yearly', 'Щороку'), ('weekly', 'Щотижня')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.balanceitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Підписка',
                'verbose_name_plural': 'Підписки',
                'ordering': ['next_payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Початкова сума')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Залишок боргу')),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Щомісячний платіж')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата погашення')),
                ('payment_day', models.PositiveSmallIntegerField(default=1, verbose_name='День платежу (число місяця)')),
                ('is_active', models.BooleanField(default=True)),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.balanceitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредити',
                'ordering': ['remaining_amount'],
            },
        ),
    ]
