# Generated by Django 4.2.14 on 2026-01-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заборгованість', 'verbose_name_plural': 'Заборгованості'},
        ),
    ]
